### ISSUE TITLE
CSE251_Programming_in_C/Project2/elevator.c

### ISSUE THREAD

**Issue by wHITEwATERISME** [Frodocz/CSE251_Programming_in_C#1]
在你的StateMoving()方法中没有状态转移语句, 也就是说程序只会卡死在Moving状态中

**Comment by Frodocz** [comment]
Hi @wHITEwATERISME , 确实是我漏掉了StateMoving()里的状态转移，新的版本已经加上了。另外一些之前没注意到的Requirement比如开门3s之后关门之类的问题我也加上了。多谢！
